env:
  es6: true
  browser: true
  commonjs: true
  jest: true

extends: ['htmlacademy/es6']

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 6
  sourceType: module

settings:
  react:
    version: '16'
